<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ItemsTableSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        DB::table('items')->insert([
            [
                'name' => 'アセット01',
                'description' => 'アイコン：初期登録時から所有',
                'type' => 'icon',
                'rarity' => 'common',
                'image_name' => 'ast01',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'アセット02',
                'description' => 'アイコン：初期登録時から所有',
                'type' => 'icon',
                'rarity' => 'common',
                'image_name' => 'ast02',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'アセット03',
                'description' => 'アイコン：初期登録時から所有',
                'type' => 'icon',
                'rarity' => 'common',
                'image_name' => 'ast03',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => '初心者',
                'description' => '称号：初期登録時から所有',
                'type' => 'title',
                'rarity' => 'common',
                'image_name' => 'title01',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => '伝説の勇者',
                'description' => '称号：特別な条件でのみ取得できる',
                'type' => 'title',
                'rarity' => 'epic',
                'image_name' => 'title99',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => '伝説の勇者アイコン',
                'description' => 'アイコン：特別な条件でのみ取得できる',
                'type' => 'icon',
                'rarity' => 'epic',
                'image_name' => 'icon99',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'ガチャチケ',
                'description' => 'アイテム：いつか使えるようになる',
                'type' => 'item',
                'rarity' => 'common',
                'image_name' => 'item01',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'ランキング作成チケット',
                'description' => 'アイテム：ランキング作成に使用',
                'type' => 'item',
                'rarity' => 'common',
                'image_name' => 'item02',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => '動物アイコン',
                'description' => 'アイコン：特定タグをつけた際に獲得',
                'type' => 'icon',
                'rarity' => 'common',
                'image_name' => 'animal_default',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'アニメアイコン',
                'description' => 'アイコン：特定タグをつけた際に獲得',
                'type' => 'icon',
                'rarity' => 'common',
                'image_name' => 'anime_default',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => '本アイコン',
                'description' => 'アイコン：特定タグをつけた際に獲得',
                'type' => 'icon',
                'rarity' => 'common',
                'image_name' => 'book_default',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'キャラクターアイコン',
                'description' => 'アイコン：特定タグをつけた際に獲得',
                'type' => 'icon',
                'rarity' => 'common',
                'image_name' => 'character_default',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'お笑いアイコン',
                'description' => 'アイコン：特定タグをつけた際に獲得',
                'type' => 'icon',
                'rarity' => 'common',
                'image_name' => 'comedy_default',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => '食べ物アイコン',
                'description' => 'アイコン：特定タグをつけた際に獲得',
                'type' => 'icon',
                'rarity' => 'common',
                'image_name' => 'food_default',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'ゲームアイコン',
                'description' => 'アイコン：特定タグをつけた際に獲得',
                'type' => 'icon',
                'rarity' => 'common',
                'image_name' => 'game_default',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'アイドルアイコン',
                'description' => 'アイコン：特定タグをつけた際に獲得',
                'type' => 'icon',
                'rarity' => 'common',
                'image_name' => 'idol_default',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'マンガアイコン',
                'description' => 'アイコン：特定タグをつけた際に獲得',
                'type' => 'icon',
                'rarity' => 'common',
                'image_name' => 'manga_default',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => '映画アイコン',
                'description' => 'アイコン：特定タグをつけた際に獲得',
                'type' => 'icon',
                'rarity' => 'common',
                'image_name' => 'movie_default',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => '音楽アイコン',
                'description' => 'アイコン：特定タグをつけた際に獲得',
                'type' => 'icon',
                'rarity' => 'common',
                'image_name' => 'music_default',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'スポーツアイコン',
                'description' => 'アイコン：特定タグをつけた際に獲得',
                'type' => 'icon',
                'rarity' => 'common',
                'image_name' => 'sports_default',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => '旅行アイコン',
                'description' => 'アイコン：特定タグをつけた際に獲得',
                'type' => 'icon',
                'rarity' => 'common',
                'image_name' => 'travel_default',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'VTuberアイコン',
                'description' => 'アイコン：特定タグをつけた際に獲得',
                'type' => 'icon',
                'rarity' => 'common',
                'image_name' => 'vtuber_default',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'YouTubeアイコン',
                'description' => 'アイコン：特定タグをつけた際に獲得',
                'type' => 'icon',
                'rarity' => 'common',
                'image_name' => 'youtube_default',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'わちゃわちゃアイコン(原画)',
                'description' => 'アイコン：原画仕様の特別なアイコン',
                'type' => 'icon',
                'rarity' => 'common',
                'image_name' => 'sp01',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'ぷりめアイコン(原画)',
                'description' => 'アイコン：原画仕様の特別なアイコン',
                'type' => 'icon',
                'rarity' => 'common',
                'image_name' => 'sp02',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'きゃびーアイコン(原画)',
                'description' => 'アイコン：原画仕様の特別なアイコン',
                'type' => 'icon',
                'rarity' => 'common',
                'image_name' => 'sp03',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'わちゃわちゃアイコン',
                'description' => 'アイコン：特別なアイコン',
                'type' => 'icon',
                'rarity' => 'common',
                'image_name' => 'sp04',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'ぷりめアイコン',
                'description' => 'アイコン：特別なアイコン',
                'type' => 'icon',
                'rarity' => 'common',
                'image_name' => 'sp05',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'きゃびーアイコン',
                'description' => 'アイコン：特別なアイコン',
                'type' => 'icon',
                'rarity' => 'common',
                'image_name' => 'sp06',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);
    }
}
